#!/usr/bin/env node
/**
 * One-shot migration: re-encrypt every v1 ciphertext under v2 (HKDF +
 * AAD bound to (field, bindingId)). Idempotent — rows that already start
 * with `v2:` are skipped, so the script can be re-run after a partial
 * outage without double-encrypting anything.
 *
 * Implements M1 from docs/cybersecurity-audit-2026-05-09.md.
 *
 * Usage:
 *   SETTINGS_ENCRYPTION_KEY=… node scripts/reencrypt-secrets.js [--dry-run]
 *
 * Exit codes:
 *   0  All v1 rows successfully migrated (or none found).
 *   1  Decrypt failure on at least one row (key mismatch, corruption).
 *   2  Database / config error / crypto self-check failure.
 *
 * The script imports its crypto primitives (HKDF salt/info, AAD format,
 * AES parameters) from lib/secrets.js — DO NOT duplicate them here. A
 * known-answer self-check runs before any database row is touched: if the
 * lib drifts away from the format used to encrypt existing data, the
 * self-check fails fast and aborts before producing unreadable rows.
 */
const { Pool } = require('pg');

const DEFAULT_DATABASE_URL = 'postgresql://transkription:transkription@localhost:5432/transkription';
const DRY_RUN = process.argv.includes('--dry-run');

// Hardcoded v2 vector. Generated by encrypting `SELF_CHECK_PLAINTEXT`
// with SETTINGS_ENCRYPTION_KEY=SELF_CHECK_IKM, AAD context
// {field: 'self-check', bindingId: '42'}, IV = ascii('selfcheckiv0').
// If lib/secrets.js HKDF_SALT, HKDF_INFO, AAD format, KEY_LENGTH, or
// IV_LENGTH change, decryption of this vector fails — the migration
// then aborts before mangling production data. Re-generate this block
// only as part of a deliberate format upgrade.
const SELF_CHECK_IKM = 'reencrypt-self-check-key-do-not-use-32';
const SELF_CHECK_PLAINTEXT = 'reencrypt-self-check OK';
const SELF_CHECK_CIPHERTEXT =
  'v2:c2VsZmNoZWNraXYw:+n69QOqRIGMMMZkIkmFzRg==:X9WbQ3uGE4mHqXCGnxCK3rmp2EwoqUI=';
const SELF_CHECK_CONTEXT = { field: 'self-check', bindingId: '42' };

async function loadSecretsModule() {
  return import('../lib/secrets.js');
}

async function runSelfCheck() {
  const previousKey = process.env.SETTINGS_ENCRYPTION_KEY;
  process.env.SETTINGS_ENCRYPTION_KEY = SELF_CHECK_IKM;
  try {
    const { decryptSecret } = await loadSecretsModule();
    const got = decryptSecret(SELF_CHECK_CIPHERTEXT, SELF_CHECK_CONTEXT);
    if (got !== SELF_CHECK_PLAINTEXT) {
      const expected = JSON.stringify(SELF_CHECK_PLAINTEXT);
      const actual = got == null ? 'null (auth tag mismatch / decrypt failure)' : JSON.stringify(got);
      throw new Error(
        `lib/secrets.js v2 format drifted from the migration self-check vector.\n` +
        `  expected ${expected}\n  got      ${actual}\n` +
        `  Aborting before any production row is touched.`,
      );
    }
  } finally {
    if (previousKey === undefined) delete process.env.SETTINGS_ENCRYPTION_KEY;
    else process.env.SETTINGS_ENCRYPTION_KEY = previousKey;
  }
}

async function migrateTarget(client, target, secrets) {
  console.log(`\n=== ${target.label} ===`);
  let rows;
  try {
    rows = await client.query(target.select);
  } catch (error) {
    if (error?.code === '42P01' || error?.code === '42703') {
      console.log(`  table/column missing — skipping`);
      return { migrated: 0, skipped: 0, failed: 0 };
    }
    throw error;
  }
  let migrated = 0;
  let skipped = 0;
  let failed = 0;
  for (const row of rows.rows) {
    if (!secrets.isLegacySecret(row.ciphertext)) {
      skipped += 1;
      continue;
    }
    const context = { field: target.field, bindingId: row.binding_id };
    const plain = secrets.decryptSecret(row.ciphertext, context);
    if (plain == null) {
      failed += 1;
      console.error(`  FAIL: row id=${row.id} could not be decrypted with the v1 key`);
      continue;
    }
    const next = secrets.encryptSecret(plain, context);
    if (next == null) {
      failed += 1;
      console.error(`  FAIL: row id=${row.id} could not be re-encrypted under v2`);
      continue;
    }
    if (DRY_RUN) {
      migrated += 1;
      continue;
    }
    await client.query(target.update, [next, row.id]);
    migrated += 1;
  }
  console.log(`  migrated=${migrated}  already-v2=${skipped}  failed=${failed}${DRY_RUN ? '  (dry-run)' : ''}`);
  return { migrated, skipped, failed };
}

function buildTargets(secretContexts) {
  return [
    {
      label: 'settings.mistral_api_key_encrypted',
      field: secretContexts.mistralApiKey,
      select: 'SELECT id, user_id AS binding_id, mistral_api_key_encrypted AS ciphertext FROM settings WHERE mistral_api_key_encrypted IS NOT NULL',
      update: 'UPDATE settings SET mistral_api_key_encrypted = $1 WHERE id = $2',
    },
    {
      label: 'organization_integrations.config_encrypted',
      field: secretContexts.integrationConfig,
      select: 'SELECT id, organization_id AS binding_id, config_encrypted AS ciphertext FROM organization_integrations WHERE config_encrypted IS NOT NULL',
      update: 'UPDATE organization_integrations SET config_encrypted = $1 WHERE id = $2',
    },
    {
      label: 'vexa_user_tokens.api_key_encrypted',
      field: secretContexts.vexaUserToken,
      select: 'SELECT id, organization_id AS binding_id, api_key_encrypted AS ciphertext FROM vexa_user_tokens WHERE api_key_encrypted IS NOT NULL',
      update: 'UPDATE vexa_user_tokens SET api_key_encrypted = $1 WHERE id = $2',
    },
  ];
}

async function main() {
  try {
    await runSelfCheck();
  } catch (error) {
    console.error('Crypto self-check failed:');
    console.error(`  ${error?.message || error}`);
    process.exit(2);
  }

  if (!process.env.SETTINGS_ENCRYPTION_KEY) {
    console.error('SETTINGS_ENCRYPTION_KEY ist nicht gesetzt.');
    process.exit(2);
  }

  const secrets = await loadSecretsModule();
  const targets = buildTargets(secrets.SECRET_CONTEXTS);

  const pool = new Pool({
    connectionString: process.env.DATABASE_URL || DEFAULT_DATABASE_URL,
  });
  const client = await pool.connect();
  try {
    if (!DRY_RUN) await client.query('BEGIN');
    const totals = { migrated: 0, skipped: 0, failed: 0 };
    for (const target of targets) {
      const r = await migrateTarget(client, target, secrets);
      totals.migrated += r.migrated;
      totals.skipped += r.skipped;
      totals.failed += r.failed;
    }
    if (!DRY_RUN) {
      if (totals.failed > 0) {
        await client.query('ROLLBACK');
        console.error(`\nROLLBACK — ${totals.failed} row(s) could not be decrypted. No changes were committed.`);
        process.exit(1);
      } else {
        await client.query('COMMIT');
      }
    }
    console.log(`\nTOTAL: migrated=${totals.migrated}  already-v2=${totals.skipped}  failed=${totals.failed}${DRY_RUN ? '  (dry-run)' : ''}`);
    process.exit(totals.failed > 0 ? 1 : 0);
  } catch (error) {
    if (!DRY_RUN) {
      try { await client.query('ROLLBACK'); } catch { /* ignore */ }
    }
    console.error('Migration aborted:', error?.message || error);
    process.exit(2);
  } finally {
    client.release();
    await pool.end();
  }
}

main();
